### PR TITLE
Added docs for getProof, transactionSerializer, and getArgsFromTransactionDepositedOpaqueData.

### PR DESCRIPTION
**Pull request by alexdwagner**
Still learning this codebase so let me know if any changes are needed :)

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@alexdwagner 

Thanks Alex! Looks like the linter is picking up a few formatting differences. Can you please update?

**Comment by alexdwagner** [comment]
> @alexdwagner
> 
> Thanks Alex! Looks like the linter is picking up a few formatting differences. Can you please update?

yes of course! will do

**Comment by zencephalon** [comment]
Hey @alexdwagner ! Thanks for starting this. Could U format these docs to follow the same format as the rest of the docs on the site? U can also remove the extra sections at the end of each doc. I think many of the examples won't work as written, particularly because the imports seem off, since people often refer to doc examples to start writing code this feels important to get right. U can refer to `.test` files as a way to help construct examples.

**Comment by alexdwagner** [comment]
Hey Matt, yes, sorry for the delay! Will push these changes in the next couple of days.On Jan 2, 2024, at 6:32 PM, Matthew Bunday ***@***.***> wrote:﻿
Hey @alexdwagner ! Thanks for starting this. Could U format these docs to follow the same format as the rest of the docs on the site? U can also remove the extra sections at the end of each doc. I think many of the examples won't work as written, particularly because the imports seem off, since people often refer to doc examples to start writing code this feels important to get right. U can refer to .test files as a way to help construct examples.

**Comment by alexdwagner** [comment]
Ok, y'all. Pushed changes based on your comments here.

**Pull request merged**
